import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Component/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen">
          <Header
            logoImg="/cebu-logo.png"
            title="Welcome to the City of Cebu"
            description="Transaction Kiosk"
          />
          <div className="mt-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
